name: Django
nameon: 
  push:
    branches:
    - mainjobs: 
        build: 
          runs-on: ubuntu-latest 
          steps: 
            - run: echo “This is a build step”
        test: 
          runs-on: ubuntu-latest 
          steps: 
            - run: echo “This is a test step”
        integration: 
          runs-on: ubuntu-latest 
          steps: 
            - run: echo “This is an integration step” 
            - run: exit 1
          allow_failure: true
        prod: 
          runs-on: ubuntu-latest 
          steps: 
            - run: echo “This is a deploy step”
        artifact:
          runs-on: ubuntu-latest
          steps:
            - run: echo "hello" > hello.txt
          artifacts:   
            paths: [hello.json]
