name: Django # workflow 
on: push:
branches: # similar to “only” in GitLab  
  - mainjobs: build: runs-on: ubuntu-latest # similar to “image” in GitLab 
  steps: 
    - uses: actions/checkout@v2  
    - name: Setup python    
    uses: actions/setup-python@v2    
    with:      python-version: '3.6'  
    - run: |      
      pip3 install --upgrade virtualenv      
      virtualenv env      
      source env/bin/activate      
      pip install -r requirements.txt      
      python manage.py checktest: runs-on: ubuntu-latest needs: build steps: - uses: actions/checkout@v2  - name: Setup python    
      uses: actions/setup-python@v2    
      with:      
        python-version: '3.6'  
      
      - run: |      
        pip3 install --upgrade virtualenv      
        virtualenv env      
        source env/bin/activate      
        pip install -r requirements.txt      
        python manage.py test taskManagerintegration: runs-on: ubuntu-latest needs: test steps: - run: echo “This is an integration step” - run: exit 1 continue-on-error: trueprod: runs-on: ubuntu-latest needs: integration steps: - run: echo “This is a deploy step.”
