name: Django # workflow 
on: 
  push:
    branches:
        - master
jobs: 
  build: 
    runs-on: ubuntu-latest # similar to “image” in GitLab 
    steps: 
      - uses: actions/checkout@v2 
      - name: Setup Python
        uses: actions/setup-python@v2    
        with:      
          python-version: "3.6"
      - run: |
          pip3 install --upgrade virtualenv      
          virtualenv env      
          source env/bin/activate      
          pip install -r requirements.txt      
          python manage.py check




  test: 
      runs-on: ubuntu-latest # similar to “image” in GitLab 
      steps: 
        - uses: actions/checkout@v2
        - name: Setup Python

          uses: actions/setup-python@v2    
          with:      
            python-version: "3.6"
        - run: |
            pip3 install --upgrade virtualenv      
            virtualenv env      
            source env/bin/activate      
            pip install -r requirements.txt      
            python manage.py test taskManager
            
  oast-frontend:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10.x'
      - run: npm install
      - run: docker run --rm -v $(pwd):/src hysnsec/retire --outputformat json --outputpath retirejs-report.json --severity high
        continue-on-error: true
      - uses: actions/upload-artifact@v2
        with:
          name: RetireJS
          path: retirejs-report.json
        if: always()
    



